<?php
return [
    'default_title' => 'Moneytable | Human Resource Manager',
    'path' => [
        'country' => '/config/country.php',
        'timezone' => '/config/timezone.php',
        'language' => '/config/language.php',
        'lang' => '/config/lang.php',
        'verifier' => 'http://envato.wmlab.in/',
        'config' => '/config/config.php',
        'mail' => '/config/mail.php',
        'service' => '/config/services.php',
    ],
    'item_code' => 'EZ0303',
    'ignore_var' => array('_token','config_type','ajax_submit','domain'),
    'upload_path' => [
        'logo' => 'uploads/logo/',
        'attachments' => 'uploads/attachments/',
        'profile_image' => 'uploads/profile_image/',
        'attendance' => 'uploads/attendance/',
        'backup' => 'uploads/backup/',
    ],
    'system_default' => [
        'application_name' => 'Moneytable HRM',
        'timezone_id' => '258',
        'default_currency' => 'Thai Baht',
        'default_currency_symbol' => '‎฿',
        'default_language' => 'en',
        'direction' => 'ltr',
        'allowed_upload_file' => 'pdf,doc,docx,xls,xlsx,jpg,jpeg',
        'error_display' => 1,
        'currency_decimal' => '2',
        'currency_position' => 'prefix',
        'logo' => 'logo.png',
        'application_setup_info' => '1',
        'textarea_limit' => '300',
        'notification_position' => 'toast-top-right',
        'installation_path' => 1,
        'celebration_days' => 30,
        'multilingual' => 1,
        'leave_approval_level' => 'single',
        'expense_approval_level' => 'single',
        'auto_lock_daily_report' => 1,
        'payroll_days' => 'from_date',
        'subordinate' => 0,
        'enable_future_attendance' => 0,
        'auto_lock_attendance_days' => 2,
        'enable_registration' => 0,
        'sub_task_rating' => 0,
        'login_with' => 'username'
    ],
    'mail_default' => [
        'driver' => 'log',
        'from_name' => 'Moneytable HRM',
        'from_address' => 'hrm@moneytable.com'
    ],
    'default_role' => 'admin',
    'default_department' => 'System Administration',
    'default_designation' => 'System Administrator',
];
